config/routes.rb
Rails.application.routes.draw do
  resources :channels
  resources :users
  resources :messages
  root to: 'channels#index'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :messages, dependent: :destroy
  has_many :contributors, through: :messages, source: :user
  has_many :private_conversations
  has_many :private_contributors, through: :private_conversations, source: :user

  accepts_nested_attributes_for :private_conversations, allow_destroy: true

  validates :name, presence: true,
                  length: { maximum: 100 },
                  uniqueness: true,
                  case_sensitive: false

  def is_public?
    !private
  end

  def is_private?
    private
  end

  def authorized_contributor?(user)
    is_public? || user == self.user ||
    private_contributors.include?(user)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :channel

  validates :content, presence: true, length: { maximum: 3000 }

  def is_edited?
    updated_at != created_at
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 3000 }
  
  def is_edited?
    updated_at != created_at
  end
end

app/models/private_conversation.rb
class PrivateConversation < ApplicationRecord
  belongs_to :user
  belongs_to :channel
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  has_many :messages, dependent: :destroy
  has_many :channels, through: :messages
  has_many :private_conversations
  has_many :private_channels, through: :private_conversations, source: :channel

  validates :name, presence: true,
                  length: { maximum: 50 },
                  uniqueness: true
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :require_login
  before_action :channel, only: %i[show edit update destroy]
  before_action :users, only: %i[new edit create]
  before_action :can_contribute, only: [:show]

  def index
    @channels = Channel.all.select do |channel|
      channel.authorized_contributor?(current_user)
    end
  end

  def show
    @messages = channel.messages
    @message = Message.new
  end

  def new
    @channel = Channel.new
    @channel.private_conversations.build
  end

  def edit
  end

  def create
    new_params = massage_params(channel_params)
    @channel = Channel.new(new_params)

    if @channel.save
      redirect_to channel_path(channel)
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if channel.update(massage_params(channel_params))
        format.html { redirect_to channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: channel }
      else
        format.html { render :edit }
        format.json { render json: channel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def can_contribute
    redirect_to action: :index unless channel.authorized_contributor?(current_user)
  end

  def channel
    @channel ||= Channel.friendly.find(params[:id])
  end

  def channel_params
    params.require(:channel).permit(:id, :private, :name,
                                    private_conversations_attributes: [user_id: []]
                                  )
  end

  def massage_params(params)
    new_params = params.merge({ user_id: current_user.id })

    if new_params['private'] == 'true'
      private_user_ids = new_params['private_conversations_attributes']['0']['user_id']

      private_conv_attr = {}.tap do |hash|
        private_user_ids.each_with_index do |user_id, index|
          hash[index.to_s.to_sym] = { user_id: user_id }
        end
      end

      new_params.merge({ private_conversations_attributes: private_conv_attr })
    else
      new_params
    end
  end

  def users
    @users ||= User.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :message, only: %i[show edit update destroy]
  before_action :user

  def create
    message = Message.new(message_params)
    message.content = white_list.sanitize(message.content)
    message.user = user

    message.save
    ActionCable.server.broadcast 'messages',
      message: message.content,
      user: message.user.name
    head :ok
  end

  def edit
  end

  def update
    message.update_attributes(message_params)
  end

  def destroy
    message.destroy
  end

  private

  def message_params
    params.require(:message).permit(:content, :channel_id, :user_id)
  end

  def user
    @user ||= current_user
  end

  def white_list
    @white_list_sanitizer ||= Rails::Html::WhiteListSanitizer.new
  end

  def message
    @message ||= Message.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[show edit index]
  before_action :user, only: %i[show edit]

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'Successful signup!'
    else
      flash[:error] = 'Oops, an error occured. Please try again later.'
    end

    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :email, :password)
  end

  def user
    @user ||= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
  def generate_private_options(users)
    users.reject { |user| user == current_user }.map { |user| [user.name, user.id] }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/_form.html.erb
<%= form_for(channel) do |f| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(channel.errors.count, 'error') %> prohibited your channel from being created:</h3>
      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Channel name:' %>
  </div>

  <div class="form-group">
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :private %>
  </div>

  <div class="form-group">
    <%= f.check_box :private, {}, 'true', 'false' %>
  </div>

  <%= f.fields_for :private_conversations do |ff| %>
    <div class="form-group">
      <%= ff.label :user_id, 'private contributors' %>
    </div>

    <div class="form-group selectize">
      <div style="max-width: 300px;">
        <%= ff.select :user_id, generate_private_options(users), { include_hidden: false }, { multiple: true } %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

<script>
  $(document).on('turbolinks:load', function() {
    $('.selectize select').selectize({ maxItems: null });
  });
</script>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel, users: @users %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<ul>
  <% @channels.each do |channel| %>
    <li>
      <%= link_to "#{channel.name}", channel_path(channel) %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel, users: @users %>

app/views/channels/show.html.erb
<div class="messages-container">
  <h2><%= @channel.name %></h2>

  <div class="messages">
    <%= render partial: 'messages/message', collection: @channel.messages %>
  </div>

  <%= render('messages/form', message: @message, channel: @channel) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ptalk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <div>
      <% if signed_in? %>
        Signed in as: <%= current_user.name %>
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', sign_in_path %>
      <% end %>
    </div>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message, remote: true) do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id if current_user %>
  <%= f.hidden_field :channel_id, value: channel.id %>

  <div class="form-group">
    <%= f.label :content, 'Type your message here:' %>
    <div>
      <%= f.text_area :content %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit 'Post', id: 'post_message', hidden: true %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<p><strong><%= message.user.name %>:</strong> <%= message.content %></p>

app/views/messages/edit.html.erb
<%= render 'form', { post: @message, current_user: @user } %>

app/views/messages/index.html.erb
<div class="posts-container">
  <ul class="post-list">
    <% @messages.each do |message| %>
      <li><%= render 'message', { message: message, current_user: @user } %></li>
    <% end %>
  </ul>

  <div class="post-form">
    <%= render 'form', { current_user: @user } %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being created:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id if current_user %>

  <div class="form-group">
    <%= f.text_area :content %>
  </div>

  <div class="form-group">
    <%= f.submit 'Post' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="posts-container">
  <ul class="post-list">
    <% @posts.each do |post| %>
      <li><%= render 'post', { post: post, current_user: @user } %></li>
    <% end %>
  </ul>

  <div class="post-form">
    <%= render 'form', { current_user: @user } %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>